# -*- coding: utf-8 -*-
# Deployment settings for OneTap.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.3/s3e/makefile_builder/mkb.py', 'c:/Users/Randy/Documents/MarmaladeGames/OneTap/OneTap.mkb', '--buildenv=VC12X', '--debug', '--x86', '--no-ide', '--make', '--deploy-only']
mkb = 'c:/Users/Randy/Documents/MarmaladeGames/OneTap/OneTap.mkb'
mkf = ['c:\\marmalade\\7.3\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.3\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.3\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.3\\modules\\third_party\\zlib\\zlib.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Randy/Documents/MarmaladeGames/OneTap\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'OneTap'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'OneTap'
    long_caption = 'OneTap'
    version = [0, 0, 1]
    config = ['c:/Users/Randy/Documents/MarmaladeGames/OneTap/data/app.icf']
    data_dir = 'c:/Users/Randy/Documents/MarmaladeGames/OneTap/data'
    iphone_link_lib = []
    osx_ext_dll = []
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = []
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws81_ext_sdk_ref_file = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    android_external_jars = []
    android_supports_gl_texture = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    ws81_ext_sdk_ref = []
    iphone_link_opts = []
    ws81_ext_native_dll = []
    wp8_ext_managed_dll = []
    android_so = []
    osx_extra_res = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Debug_OneTap_VC12X_gcc_x86/OneTap.so',
                   'release' : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Release_OneTap_VC12X_gcc_x86/OneTap.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Debug_OneTap_VC12X_gcc_x86_tizen/OneTap.s86',
                   'release' : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Release_OneTap_VC12X_gcc_x86_tizen/OneTap.s86',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Debug_OneTap_VC12X_gcc_mips/OneTap.so',
                   'release' : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Release_OneTap_VC12X_gcc_mips/OneTap.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Debug_OneTap_VC12X_gcc_arm/OneTap.s3e',
                   'release' : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Release_OneTap_VC12X_gcc_arm/OneTap.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Debug_OneTap_VC12X_gcc_mips/OneTap.so',
                   'release' : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Release_OneTap_VC12X_gcc_mips/OneTap.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Debug_OneTap_VC12X_gcc_x86_android/OneTap.so',
                   'release' : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Release_OneTap_VC12X_gcc_x86_android/OneTap.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Debug_OneTap_VC12X_arm/OneTap.s3e',
                   'release' : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Release_OneTap_VC12X_arm/OneTap.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Debug_OneTap_VC12X_x86/OneTap.s86',
                   'release' : r'c:/Users/Randy/Documents/MarmaladeGames/OneTap/build_onetap_vc12x/Release_OneTap_VC12X_x86/OneTap.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
